# Generated by Django 4.2.5 on 2024-09-03 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.CharField(max_length=10, unique=True)),
                ('departingFlight_code', models.CharField(max_length=10)),
                ('returningFlight_code', models.CharField(max_length=10)),
                ('departure_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seats_left', models.PositiveIntegerField()),
                ('flight_class', models.CharField(choices=[('Economy', 'Economy'), ('Business', 'Business'), ('First Class', 'First Class')], default='Economy', max_length=25)),
                ('airline', models.CharField(default='Anonymous Airline', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='airport',
            name='iata_code',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.CreateModel(
            name='Flightselection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tag', models.CharField(max_length=20)),
                ('departing_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departing_flight', to='api.flight')),
                ('returning_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returning_flight', to='api.flight')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_flights', to='api.airport'),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_flights', to='api.airport'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['departure_airport'], name='api_flight_departu_6a8178_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['arrival_airport'], name='api_flight_arrival_df807d_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['departure_time'], name='api_flight_departu_4d77dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.CheckConstraint(check=models.Q(('seats_left__gte', 0)), name='seats_left_positive'),
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='price_positive'),
        ),
        migrations.AlterUniqueTogether(
            name='flight',
            unique_together={('departure_airport', 'arrival_airport', 'departure_time')},
        ),
    ]
